### ISSUE TITLE
Why not using AES instead of DES?

### ISSUE THREAD

**Issue by ostafen** [ASWLaunchs/healthSentinel#1]
Hi, I noticed that in the auth.go file, the DES algorithm is used to crypt/decrypt. 
However, since it is an outdated standard, I recommend to use AES

**Comment by ASWLaunchs** [comment]
okay ,thanks for your suggestion，I will change it later. 😊

**Comment by ASWLaunchs** [comment]
> Hi, I noticed that in the auth.go file, the DES algorithm is used to crypt/decrypt. However, since it is an outdated standard, I recommend to use AES

okay ,thanks for your suggestion，I will change it later. 😊

**Comment by ostafen** [comment]
If you want, I can submit a PR ;=)

**Comment by ASWLaunchs** [comment]
> If you want, I can submit a PR ;=)

okay , you are very welcome to submit your PR
